name: Deploy (Compose on VM)
on:
  workflow_run:
    workflows: ["Build and Push (Docker Hub)"]
    types: [completed]
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Update wedsy on VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            set -e
            cd /opt/stack
            docker compose pull wedsy
            docker compose up -d wedsy
            docker image prune -f
